Spring:
    application:
        name: dine-in-api

    datasource:
        url: ${MYSQL_URL}
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update

server:
  port: 9090

app:
  base-url: /api/v1
  cloudinary:
    cloud-name: dtbp9cnvj
    api-key: 475931139223847
    api-secret: 0vIGeqOnmT0HLFEcNaqGs9-4n1Y
  security:
    token-validity:
      access-validity: 3600
      refresh-validity: 3600
    secret: ${SECURITY_SECRET};
  domain:
    name: ${DOMAIN_NAME}
    secure: ${DOMAIN_SECURE}
    same-site: ${DOMAIN_SAME_SITE}

#spring.application.name=dine-in-api
##DATASOURCE CONFIGURATION
#spring.datasource.url=jdbc:mysql://localhost:3306/dine_in_db?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=Supriya@104
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update

