Spring:
    application:
        name: dine-in-api

    datasource:
        url: jdbc:mysql://localhost:3306/dine_in_db?createDatabaseIfNotExist=true
        username: root
        password: Supriya@104

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update

server:
  port: 9090

#spring.application.name=dine-in-api
##DATASOURCE CONFIGURATION
#spring.datasource.url=jdbc:mysql://localhost:3306/dine_in_db?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=Supriya@104
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update

